const YT_API_KEY = 'AIzaSyBvXLe69o9TZLXbVzkWd3zGTNaZhvI_EVQ';
export const YOUTUBE_API = `https://youtube.googleapis.com/youtube/v3/videos?part=snippet%2CcontentDetails%2Cstatistics&chart=mostPopular&maxResults=50&regionCode=IN&key=${YT_API_KEY}`

export const btnList = [
  "Home",
  "Trending",
  "Shorts",
  "Subscriptions",
  "Technology",
  "Fitness",
  "Health",
  "Education",
  "Programming",
  "Web Development",
  "AI & ML",
  "Startups",
  "Business",
  "Finance",
  "Investing",
  "Personal Growth",
  "Motivation",
  "Productivity",
  "Vlogs",
  "Daily Life",
  "Minimalism",
  "Photography",
  "Cinematography",
  "Editing",
  "Design",
  "UI/UX",
  "React",
  "JavaScript",
  "Podcasts",
  "Interviews",
  "Explainers",
  "Case Studies",
  "Reviews",
  "Unboxings",
  "How To",
  "Tutorials",
  "Experiments",
  "Behind The Scenes"
];